version: '3.7'
networks:
  docker-network:
services:
  ml_dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: 6000
    ports:
      - '6000:6000'
    links:
      - database_dev
    depends_on:
      - database_dev
    networks:
      - docker-network
    command: python djangoserver/manage.py runserver 0.0.0.0:5000
  database_dev:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: init12345
    networks:
      - docker-network
